name: Main

on: 
  #push:
  workflow_dispatch:
    inputs:
      tileset:
        type: choice
        options:
          - asi
          - afr
          - sa
          - na
          - aus_pac
          - eur
          - test  
      zl:
        type: string
        default: 16

jobs:
  ziplist:
    runs-on: ubuntu-22.04
    outputs:
      chunks: ${{ steps.chunks.outputs.chunks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gen tile sub-lists
        id: chunks
        run: |
          TILENAME=${{ inputs.tileset }} make -f Makefile.tiles ${{ inputs.tileset }}_tile_list_chunks
          CHUNKS=$(ls ${{ inputs.tileset }}_tile_list.* | awk -F '.' '/.+/ { printf "%s\"z_${{ inputs.tileset }}_%s.zip\"", sep, ""$2""; sep=", " }')
          #CHUNKS=$(ls ${{ inputs.tileset }}_tile_list.* | awk -v ORS=',' '{print $1}')
          echo "chunks={\"chunk\":[$CHUNKS]}" >> $GITHUB_OUTPUT


  build:
    needs: ziplist

    strategy:
      matrix: ${{ fromJSON(needs.ziplist.outputs.chunks) }}

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: America/NewYork

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install reqs
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-tk zip libgeos-dev
          python3 -m pip install -r requirements.txt
          make --version
      
      - name: always-upload-cache
        if: always()
        uses: pat-s/always-upload-cache@v3.0.1
        with:
          path: ./Ortho4XP
          key: ortho4xp-${{ matrix.chunk }}-${{ github.run_id }}
          restore-keys: |
            ortho4xp-${{ matrix.chunk }} 

      - name: Setup Ortho4XP
        run: TILENAME=${{ inputs.tileset }} make Ortho4XP

      - name: Build
        run: |
          TILENAME=${{ inputs.tileset }} make -f Makefile.tiles ${{ inputs.tileset }}_tile_list_chunks
          TILENAME=${{ inputs.tileset }} make -f Makefile.tiles -j 2 ${{ matrix.chunk }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.chunk }}

      - name: Show work
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
          echo '### {{ inputs.tileset }} : {{ matrix.chunk }}' >> $GITHUB_STEP_SUMMARY
          unzip -l {{ matrix.chunk }} *.dsf >> $GITHUB_STEP_SUMMARY
          echo '---' >> $GITHUB_STEP_SUMMARY

  info:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    environment: release

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ inputs.tileset }}_info.json

