name: Main

on: push

jobs:
  build:
    strategy:
      matrix:
        tileset: [z_aus_pac_0.zip, z_aus_pac_1.zip, z_aus_pac_2.zip, z_aus_pac_3.zip]

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: America/NewYork

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install reqs
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-tk zip
          python3 -m pip install -r requirements.txt
          make --version
      
      - name: Test
        run: make -n ${{ matrix.tileset }}

      - name: Build
        run: make -j 4 ${{ matrix.tileset }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.tileset }}
